### ISSUE TITLE
Will the codes of "Safe, Efficient, and Comfortable Velocity Control based on Reinforcement Learning for Autonomous Driving" be released?

### ISSUE THREAD

**Issue by DarrenRuan** [MeixinZhu/Velocity_control#1]
Hi,

I really like what you have done in your paper "Safe, Efficient, and Comfortable Velocity Control based on Reinforcement Learning for Autonomous Driving". Will the codes for this paper be released?

**Comment by MeixinZhu** [comment]
Sorry for the delay. The core code for the paper has been released. Thanks for your interests!
