### ISSUE TITLE
有关代码的一些疑问

### ISSUE THREAD

**Issue by Exasor** [MeixinZhu/Velocity_control#4]
您好，我阅读了您的论文和代码，有如下的一些疑问：
1. 论文中提到TTC阈值取值选择7s，而代码中为何是4.001s？
2. 论文中提到对动作的探索采用的是OU过程，而代码中为何是采用高斯噪声？
3. 论文中提到加速度的范围是[-3,3]，而代码中action_Bound=2，但舒适性奖励时为何仍使用jerk**2/3600来计算？
4. Main文件210-214行有关episode奖励的部分中，为何episode的奖励要用score /= duration这样一种平均奖励来描述而不是直接用完成一个epsode时得到的累计奖励，并且duration = data.shape[0]，其数值等于NGSIM数据集中某个跟车事件的总时刻点数（总时间/0.1），但是若中途发生碰撞，duration的数值应该是小于data.shape[0]的，这个地方不太明白
5. 论文中公式（7）中对于车距的计算公式与simulation_env文件51行的公式不一样，请问有什么考量吗？

**Comment by MeixinZhu** [comment]
I will answer your questions using English in case someone who does not understand Chinese also finds it useful.
1. 论文中提到TTC阈值取值选择7s，而代码中为何是4.001s？
Ans: We tested TTC threshold from 1s to 10s and selected 7s. So the 4.001s is just one version during development. Just change to 7s is fine. 
2. 论文中提到对动作的探索采用的是OU过程，而代码中为何是采用高斯噪声？
Ans: Using Gaussian noise is fine. 
3. 论文中提到加速度的范围是[-3,3]，而代码中action_Bound=2，但舒适性奖励时为何仍使用jerk**2/3600来计算？
Ans: Using action bound = 3 is fine. You can adjust 3600 to see the effects. The weights really influence performance. 
4. Main文件210-214行有关episode奖励的部分中，为何episode的奖励要用score /= duration这样一种平均奖励来描述而不是直接用完成一个epsode时得到的累计奖励，并且duration = data.shape[0]，其数值等于NGSIM数据集中某个跟车事件的总时刻点数（总时间/0.1），但是若中途发生碰撞，duration的数值应该是小于data.shape[0]的，这个地方不太明白
Ans: episode reward is only used to see the training process. What RL maximize is still the total cumulative rewards.
5. 论文中公式（7）中对于车距的计算公式与simulation_env文件51行的公式不一样，请问有什么考量吗？
Ans: no, just for simplity.

**Comment by Exasor** [comment]
Thanks a lot!
